version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
     - ./dynamodb-data:/home/dynamodblocal/data
    ports:
     - 8000:8000