version: '3.1'

services:

  db:
    image: neo4j:4.2.0
    restart: always
    environment:
      NEO4J_AUTH: none
      SECURE_FILE_PERMISSIONS: "yes"
    volumes:
      - ./neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687