version: '3.1'

services:

  mongo:
    image: mongo:4.4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017